import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { obtenerUsuarioSesion } from '@/lib/auth';
import { resumenExpediente } from '@/lib/industrialService';
import PrintButton from '@/app/components/PrintButton';
import SicrLogo from '@/app/components/SicrLogo';

const ETIQUETAS = {
  EMPRESA_INSTALACION: 'Empresa e instalación', VENTA: 'Venta / OC / DTE', MATERIAL: 'Materiales y lotes',
  ENERGIA: 'Energía', COMBUSTIBLE: 'Combustible', PRODUCCION: 'Producción', ENTREGA: 'Despacho y recepción',
};

export default async function DocumentoExpediente({ params }) {
  if (!(await obtenerUsuarioSesion())) redirect('/ingresar');
  const { id } = await params;
  const expediente = resumenExpediente(id);
  if (!expediente) notFound();
  const esCbam = expediente.flujo === 'CBAM';
  const informeCerrado = esCbam && expediente.estado === 'CERRADO';

  return <main className="min-h-screen bg-slate-100 text-slate-900 p-6 md:p-12 print:p-8">
    <div className="max-w-4xl mx-auto bg-white shadow-sm border border-slate-200 p-8 md:p-12 print:shadow-none print:border-0">
      <div className="flex flex-wrap justify-between gap-4 border-b border-slate-200 pb-6">
        <div className="flex items-start gap-4"><SicrLogo size="sm" contrast="dark" /><div><p className="text-xs uppercase tracking-[.22em] text-emerald-700 font-bold">{esCbam ? (informeCerrado ? 'Informe Preverificado CBAM' : 'Borrador de expediente CBAM') : 'SICR3P · expediente de evidencia'}</p><h1 className="text-2xl font-bold mt-2">{expediente.producto}</h1><p className="text-sm text-slate-600">{esCbam ? (informeCerrado ? 'Validado por verificador registrado · ' : 'Pendiente de cierre técnico · ') : ''}Período {expediente.periodo} · Flujo {expediente.flujo.replaceAll('_', ' ')}</p></div></div>
        <div className="text-right text-xs text-slate-600"><p>Expediente #{expediente.id}</p><p>Estado: {expediente.estado.replaceAll('_', ' ')}</p><p>Cobertura: {expediente.cobertura_pct}%</p></div>
      </div>
      <section className="grid md:grid-cols-2 gap-4 py-6 text-sm"><div><h2 className="font-semibold">Origen y responsable</h2><p>{expediente.proveedor}</p><p>{expediente.instalacion || 'Instalación pendiente de identificar'}</p><p>{expediente.pais_origen} → {expediente.pais_destino || 'Destino no informado'}</p></div><div><h2 className="font-semibold">Producto y trazabilidad</h2><p>Lote: {expediente.lote || 'No informado'}</p><p>Código CN: {expediente.codigo_cn || 'No informado'}</p><p>{esCbam ? (informeCerrado ? 'Informe Preverificado CBAM validado por verificador registrado; no es un certificado CBAM ni sustituye el informe formal de verificación aplicable.' : 'Borrador de trabajo con evidencia y brechas. No es un informe preverificado ni un certificado CBAM.') : 'Este documento organiza evidencia; no sustituye una verificación independiente.'}</p></div></section>
      <section><h2 className="font-semibold text-lg mb-3">Cobertura y nivel de respaldo</h2><div className="overflow-x-auto"><table className="w-full text-sm border-collapse"><thead><tr className="text-left border-b"><th className="p-2">Bloque</th><th className="p-2">Registros</th><th className="p-2">Declarado</th><th className="p-2">Documentado</th><th className="p-2">Validado en fuente</th></tr></thead><tbody>{expediente.bloques.map((bloque) => <tr key={bloque.bloque} className="border-b border-slate-100"><td className="p-2">{ETIQUETAS[bloque.bloque]}</td><td className="p-2">{bloque.cantidad}</td><td className="p-2">{bloque.declarado}</td><td className="p-2">{bloque.documentado}</td><td className="p-2">{bloque.validado_en_fuente}</td></tr>)}</tbody></table></div></section>
      <section className="mt-8"><h2 className="font-semibold text-lg mb-3">Plan de completitud</h2><p className="text-sm text-slate-600 mb-3">Cobertura actual del expediente: {expediente.plan_completitud.completitud_pct}%.</p>{expediente.plan_completitud.pendientes.length ? <ol className="list-decimal pl-5 space-y-1 text-sm">{expediente.plan_completitud.pendientes.map((pendiente, indice) => <li key={`${pendiente.tipo}-${indice}`}>{pendiente.texto}</li>)}</ol> : <p className="text-sm text-emerald-700">No hay pendientes estructurales detectados; corresponde revisar la conclusión técnica.</p>}</section>
      {esCbam && <section className="mt-8"><h2 className="font-semibold text-lg mb-3">Normas y referencias CBAM aplicadas</h2><p className="text-sm text-slate-600 mb-3">{expediente.referencias_cbam.aviso}</p><div className="space-y-2">{expediente.referencias_cbam.fuentes.map((fuente) => <div className="border border-slate-200 rounded p-3 text-sm" key={fuente.clave}><strong>{fuente.titulo}</strong><p>{fuente.referencia_legal} · versión {fuente.version || 'sin versión'} · {fuente.vinculante ? 'texto normativo' : 'referencia informativa versionada'}</p></div>)}</div></section>}
      {esCbam && expediente.referencias_cbam.valores_defecto.length > 0 && <section className="mt-8"><h2 className="font-semibold text-lg mb-3">Valores de referencia del país de origen</h2><div className="overflow-x-auto"><table className="w-full text-sm border-collapse"><thead><tr className="text-left border-b"><th className="p-2">CN</th><th className="p-2">Descripción</th><th className="p-2">Directas</th><th className="p-2">Indirectas</th><th className="p-2">Total</th></tr></thead><tbody>{expediente.referencias_cbam.valores_defecto.map((valor, indice) => <tr key={`${valor.codigo_cn}-${indice}`} className="border-b border-slate-100"><td className="p-2">{valor.codigo_cn}</td><td className="p-2">{valor.descripcion}</td><td className="p-2">{valor.emisiones_directas ?? 'N/D'}</td><td className="p-2">{valor.emisiones_indirectas ?? 'N/D'}</td><td className="p-2">{valor.emisiones_totales ?? 'N/D'}</td></tr>)}</tbody></table></div></section>}
      {expediente.hitos.length > 0 && <section className="mt-8"><h2 className="font-semibold text-lg mb-3">Hitos del Corredor Bioceánico</h2><div className="space-y-2">{expediente.hitos.map((hito) => <div className="border border-slate-200 rounded p-3 text-sm" key={hito.id}><strong>{hito.etapa.replaceAll('_', ' ')}</strong> · {hito.actor} · {hito.pais} · {hito.estado.replaceAll('_', ' ')}{hito.norma_referencia ? <p>Norma/requisito: {hito.norma_referencia}</p> : null}{hito.documento_requerido ? <p>Evidencia requerida: {hito.documento_requerido}</p> : null}</div>)}</div></section>}
      {expediente.eudr && <section className="mt-8"><h2 className="font-semibold text-lg mb-3">Evaluación EUDR del corredor</h2><p className="text-sm text-slate-600 mb-3">{expediente.eudr.aviso}</p><p className="text-xs text-slate-500 mb-3">{expediente.eudr.fechas}</p>{expediente.eudr.fuente ? <p className="text-xs text-slate-500 mb-3">{expediente.eudr.fuente.referencia_legal} · {expediente.eudr.fuente.version}</p> : null}{expediente.eudr.registros.length ? <div className="space-y-2">{expediente.eudr.registros.map((registro) => <div className="border border-slate-200 rounded p-3 text-sm" key={registro.id}><strong>{registro.aplica.replaceAll('_', ' ')}</strong><p>{registro.producto_relevante || 'Producto no informado'} · {registro.codigo_hs || 'HS/CN pendiente'} · riesgo {registro.nivel_riesgo.replaceAll('_', ' ')}</p><p>{registro.pais_produccion || 'País de producción pendiente'}{registro.geolocalizacion ? ` · ${registro.geolocalizacion}` : ''}</p>{registro.documento_legalidad ? <p>Legalidad: {registro.documento_legalidad}</p> : null}{registro.referencia_dds ? <p>DDS/TRACES: {registro.referencia_dds}</p> : null}</div>)}</div> : <p className="text-sm text-slate-600">Sin evaluación EUDR registrada.</p>}</section>}
      {expediente.trazabilidad.length > 0 && <section className="mt-8"><h2 className="font-semibold text-lg mb-3">Trazabilidad automática</h2><p className="text-sm text-slate-600 mb-3">Eventos técnicos registrados por actor y encadenados por hash.</p><div className="space-y-2">{expediente.trazabilidad.slice(0, 10).map((evento) => <div className="border border-slate-200 rounded p-3 text-sm" key={evento.id}><strong>{evento.accion.replaceAll('_', ' ')}</strong><p>{evento.entidad}{evento.entidad_id ? ` #${evento.entidad_id}` : ''} · {evento.usuario_nombre || evento.usuario_email || 'Usuario no identificado'} · {evento.fecha_registro}</p><p className="text-xs text-slate-500">SHA evento: {evento.hash_evento}</p>{evento.hash_anterior ? <p className="text-xs text-slate-500">SHA anterior: {evento.hash_anterior}</p> : null}</div>)}</div></section>}
      <p className="mt-8 text-xs text-slate-500 border-t pt-4">{expediente.aviso}</p>
      <div className="mt-6 flex gap-3 print:hidden"><Link href="/panel" className="text-sm text-emerald-700 underline">Volver al panel</Link><PrintButton /></div>
    </div>
  </main>;
}
