'use client';

import Link from 'next/link';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, BadgeCheck, CalendarCheck, Check, CreditCard, Route, ShieldCheck, WalletCards } from 'lucide-react';

const plans = [
  { id: 'ruta', name: 'Ruta', price: '$ 49.900', bag: '$ 150.000', desc: 'Para equipos que comienzan a centralizar sus servicios en ruta.', items: ['1 cuenta empresa', '2 operadores', 'Bolsa operativa mensual'] },
  { id: 'faena', name: 'Faena', price: '$ 119.900', bag: '$ 500.000', desc: 'Para cuadrillas, turnos y proveedores con más puntos de operación.', items: ['5 operadores', 'Centros de costo', 'Bolsa operativa mensual'] },
  { id: 'red', name: 'Red', price: 'A medida', bag: 'Personalizada', desc: 'Para mandantes que coordinan proveedores y varios puntos de ruta.', items: ['Operación multiempresa', 'Roles y reportes', 'Bolsa por contrato'] },
];

export default function ReservaAntaiPage() {
  const [step, setStep] = useState(1);
  const [plan, setPlan] = useState(plans[1]);
  const [form, setForm] = useState({ empresa: '', rut: '', nombre: '', email: '' });
  const [reserved, setReserved] = useState(false);
  const complete = form.empresa && form.rut && form.nombre && form.email.includes('@');

  return <main className="min-h-screen bg-[#f5f7f5] text-[#102b4a]"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link href="/antai" className="flex items-center gap-3 text-sm font-bold"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#102b4a] text-lg font-black text-white">A<span className="text-[#35b425]">i</span></span>ANTĀi <span className="font-normal text-slate-400">/ Reserva</span></Link><span className="rounded-full bg-green-50 px-3 py-1 text-xs font-bold text-green-800">DEMO DE INSCRIPCIÓN</span></div></header><div className="mx-auto max-w-5xl px-5 py-8"><Link href="/antai" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="h-4 w-4" />Volver a ANTĀi</Link><div className="mx-auto mt-8 max-w-2xl text-center"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#229719]">Reserva tu operación</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em]">Inscríbete hoy. Activa tu ruta cada mes.</h1><p className="mt-3 text-slate-600">Una reserva crea tu cuenta ANTĀi. El plan mensual habilita la administración y la bolsa operativa para pagar servicios autorizados en ruta.</p></div><div className="mx-auto mt-8 flex max-w-xl items-center justify-between text-xs font-bold">{['Reserva', 'Datos', 'Pago mensual'].map((label, index) => <div key={label} className="flex items-center gap-2"><span className={`flex h-7 w-7 items-center justify-center rounded-full ${step >= index + 1 ? 'bg-[#35b425] text-white' : 'bg-slate-200 text-slate-500'}`}>{step > index + 1 ? <Check className="h-4 w-4" /> : index + 1}</span><span className={step >= index + 1 ? 'text-[#102b4a]' : 'text-slate-400'}>{label}</span>{index < 2 && <span className="hidden h-px w-12 bg-slate-200 sm:block" />}</div>)}</div>{!reserved && <section className="mx-auto mt-10 max-w-4xl">{step === 1 && <PlanSelect plan={plan} setPlan={setPlan} next={() => setStep(2)} />}{step === 2 && <Details form={form} setForm={setForm} back={() => setStep(1)} next={() => setStep(3)} valid={complete} />}{step === 3 && <MonthlyPayment plan={plan} back={() => setStep(2)} reserve={() => setReserved(true)} />}</section>}{reserved && <Confirmation plan={plan} form={form} />}</div></main>;
}

function PlanSelect({ plan, setPlan, next }) { return <><div className="grid gap-4 md:grid-cols-3">{plans.map((item) => <button key={item.id} onClick={() => setPlan(item)} className={`rounded-2xl border p-5 text-left transition ${plan.id === item.id ? 'border-[#35b425] bg-green-50 shadow-sm' : 'border-slate-200 bg-white hover:border-green-300'}`}><div className="flex items-center justify-between"><h2 className="text-lg font-black">{item.name}</h2>{plan.id === item.id && <span className="flex h-5 w-5 items-center justify-center rounded-full bg-[#35b425] text-white"><Check className="h-3 w-3" /></span>}</div><p className="mt-3 text-2xl font-black">{item.price}<span className="text-xs font-medium text-slate-500"> {item.price !== 'A medida' && '/ mes'}</span></p><p className="mt-3 min-h-12 text-sm text-slate-600">{item.desc}</p><div className="mt-5 rounded-xl bg-white/80 p-3"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-[#229719]">Bolsa operativa demo</p><p className="mt-1 text-sm font-black">{item.bag}</p></div><ul className="mt-5 space-y-2 text-xs text-slate-600">{item.items.map((text) => <li key={text} className="flex gap-2"><Check className="h-4 w-4 text-[#229719]" />{text}</li>)}</ul></button>)}</div><div className="mt-6 flex justify-end"><button onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-[#102b4a] px-5 py-3 text-sm font-bold text-white">Continuar con {plan.name}<ArrowRight className="h-4 w-4" /></button></div></>; }
function Details({ form, setForm, back, next, valid }) { const fields = [['empresa', 'Empresa o razón social', 'text'], ['rut', 'RUT empresa', 'text'], ['nombre', 'Nombre de contacto', 'text'], ['email', 'Correo de contacto', 'email']]; return <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-green-100 text-[#229719]"><Route className="h-5 w-5" /></span><div><h2 className="text-xl font-black">Datos para tu reserva</h2><p className="text-sm text-slate-500">Usaremos estos datos para preparar tu cuenta demo.</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{fields.map(([key, label, type]) => <label key={key} className={key === 'empresa' ? 'sm:col-span-2' : ''}><span className="text-xs font-bold text-slate-500">{label}</span><input type={type} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-[#35b425]" /></label>)}</div><div className="mt-6 flex justify-between"><button onClick={back} className="rounded-xl px-4 py-3 text-sm font-bold text-slate-500">Atrás</button><button disabled={!valid} onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-[#102b4a] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Ver pago mensual<ArrowRight className="h-4 w-4" /></button></div></div>; }
function MonthlyPayment({ plan, back, reserve }) { return <div className="grid gap-5 md:grid-cols-[1fr_.8fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.15em] text-[#229719]">Paso demostrativo</p><h2 className="mt-2 text-2xl font-black">Activa tu plan mensual</h2><p className="mt-2 text-sm text-slate-600">En producción, este paso se conecta a Webpay. En esta versión sólo muestra la experiencia de pago.</p><div className="mt-6 rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-3"><CreditCard className="h-6 w-6 text-[#229719]" /><div><p className="text-sm font-bold">Tarjeta débito, crédito o prepago</p><p className="text-xs text-slate-500">Checkout seguro Webpay</p></div></div><div className="mt-4 flex gap-2"><span className="h-8 w-12 rounded bg-slate-100" /><span className="h-8 w-12 rounded bg-slate-100" /><span className="h-8 w-12 rounded bg-slate-100" /></div></div><div className="mt-6 flex justify-between"><button onClick={back} className="rounded-xl px-4 py-3 text-sm font-bold text-slate-500">Atrás</button><button onClick={reserve} className="rounded-xl bg-[#35b425] px-5 py-3 text-sm font-bold text-white">Simular pago y reservar</button></div></section><aside className="rounded-3xl bg-[#102b4a] p-6 text-white"><WalletCards className="h-7 w-7 text-[#73db65]" /><p className="mt-6 text-sm text-slate-300">Plan elegido</p><h3 className="text-2xl font-black">ANTĀi {plan.name}</h3><div className="mt-7 border-t border-white/15 pt-4"><p className="text-xs text-slate-300">Pago mensual</p><p className="mt-1 text-2xl font-black">{plan.price}</p></div><div className="mt-5 rounded-xl bg-white/10 p-3"><p className="text-xs text-slate-300">Después de pagar</p><p className="mt-1 text-sm font-bold">Se habilita la bolsa {plan.bag} para servicios autorizados.</p></div></aside></div>; }
function Confirmation({ plan, form }) { return <section className="mx-auto mt-10 max-w-2xl rounded-3xl border border-green-200 bg-white p-8 text-center shadow-sm"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-green-100 text-[#229719]"><CalendarCheck className="h-7 w-7" /></span><p className="mt-5 text-xs font-bold uppercase tracking-[.15em] text-[#229719]">Reserva registrada · Demo</p><h2 className="mt-2 text-3xl font-black">Tu ruta ya tiene punto de partida.</h2><p className="mx-auto mt-3 max-w-lg text-sm leading-relaxed text-slate-600">Mostramos que <b>{form.empresa}</b> reserva ANTĀi {plan.name}, paga su mensualidad y recibe una bolsa operativa de <b>{plan.bag}</b> para administrar pagos de ruta autorizados.</p><div className="mt-6 grid grid-cols-3 gap-3 text-left text-xs"><div className="rounded-xl bg-slate-50 p-3"><BadgeCheck className="h-4 w-4 text-[#229719]" /><p className="mt-2 font-bold">Cuenta creada</p></div><div className="rounded-xl bg-slate-50 p-3"><ShieldCheck className="h-4 w-4 text-[#229719]" /><p className="mt-2 font-bold">Plan mensual</p></div><div className="rounded-xl bg-slate-50 p-3"><WalletCards className="h-4 w-4 text-[#229719]" /><p className="mt-2 font-bold">Bolsa operativa</p></div></div><Link href="/antai" className="mt-7 inline-flex rounded-xl bg-[#102b4a] px-5 py-3 text-sm font-bold text-white">Volver a ANTĀi</Link></section>; }
